//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardFMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class checklistquestion
    {
        public checklistquestion()
        {
            this.checklist_question_info = new HashSet<checklist_question_info>();
            this.question_value = new HashSet<question_value>();
        }
    
        public int id { get; set; }
        public int checklist_id { get; set; }
        public string code { get; set; }
    
        public virtual checklist checklist { get; set; }
        public virtual ICollection<checklist_question_info> checklist_question_info { get; set; }
        public virtual ICollection<question_value> question_value { get; set; }
    }
}
