//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardFMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class country
    {
        public country()
        {
            this.country_info = new HashSet<country_info>();
            this.country_indicator = new HashSet<country_indicator>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
    
        public virtual ICollection<country_info> country_info { get; set; }
        public virtual ICollection<country_indicator> country_indicator { get; set; }
    }
}
