//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardFMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class indicatorgroup
    {
        public indicatorgroup()
        {
            this.indicators = new HashSet<indicator>();
            this.indicator_group_info = new HashSet<indicator_group_info>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
    
        public virtual ICollection<indicator> indicators { get; set; }
        public virtual ICollection<indicator_group_info> indicator_group_info { get; set; }
    }
}
