//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardFMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class indicator_group_info
    {
        public int indicatorgroup_id { get; set; }
        public int language_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
    
        public virtual indicatorgroup indicatorgroup { get; set; }
        public virtual language language { get; set; }
    }
}
