//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardFMP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class indicator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public indicator()
        {
            //this.country_indicator = new HashSet<country_indicator>();
            this.indicator_info = new HashSet<indicator_info>();
        }

        public int id { get; set; }
        public int? checklist_id { get; set; }
        public int objective_id { get; set; }
        public int indicatorgroup_id { get; set; }
        public string code { get; set; }
        public string mode { get; set; }
        public string frequency { get; set; }
        public bool? Q1 { get; set; }
        public bool? Q2 { get; set; }
        public bool? Q3 { get; set; }
        public bool? Q4 { get; set; }
        public int? anual_calculation_id { get; set; }
        public int? responsible { get; set; }
        public int? contact { get; set; }
        public string inputtype { get; set; }
        public int? orden { get; set; }
        public Guid clave { get;}

        [ForeignKey("checklist_id")]
        public virtual checklist checklist { get; set; }
        [ForeignKey("indicatorgroup_id")]
        public virtual indicatorgroup indicatorgroup { get; set; }
        [ForeignKey("objective_id")]
        public virtual objective objective { get; set; }
        //[ForeignKey("id")]
        //public virtual country_indicator country_indicator { get; set; }
        //[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<country_indicator> country_indicator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<indicator_info> indicator_info { get; set; }
    }
}
