//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardFMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class language
    {
        public language()
        {
            this.checklist_question_info = new HashSet<checklist_question_info>();
            this.country_info = new HashSet<country_info>();
            this.indicator_group_info = new HashSet<indicator_group_info>();
            this.indicator_info = new HashSet<indicator_info>();
            this.objective_info = new HashSet<objective_info>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string code { get; set; }
    
        public virtual ICollection<checklist_question_info> checklist_question_info { get; set; }
        public virtual ICollection<country_info> country_info { get; set; }
        public virtual ICollection<indicator_group_info> indicator_group_info { get; set; }
        public virtual ICollection<indicator_info> indicator_info { get; set; }
        public virtual ICollection<objective_info> objective_info { get; set; }
    }
}
