//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardFMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class question_value
    {
        public int country_indicator_country_id { get; set; }
        public int country_indicator_indicator_id { get; set; }
        public int checklistquestion_id { get; set; }
        public Nullable<int> value { get; set; }
        public Nullable<int> target { get; set; }
    
        public virtual checklistquestion checklistquestion { get; set; }
        public virtual country_indicator country_indicator { get; set; }
    }
}
