//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardFMP.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class checklistquestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public checklistquestion()
        {
            this.question_value = new HashSet<question_value>();
        }
    
        public int id { get; set; }
        public Nullable<int> language_id { get; set; }
        public int checklist_id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public string description { get; set; }
    
        public virtual checklist checklist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<question_value> question_value { get; set; }
        public virtual language language { get; set; }
    }
}
